Create a NumPy array of numbers from 10 to 50.



In [2]:
import numpy as np
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Generate a 3×3 identity matrix.


In [10]:
arrr=np.arange(100).reshape(5,5,4)
print(arrr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]]

 [[20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]
  [32 33 34 35]
  [36 37 38 39]]

 [[40 41 42 43]
  [44 45 46 47]
  [48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]]

 [[60 61 62 63]
  [64 65 66 67]
  [68 69 70 71]
  [72 73 74 75]
  [76 77 78 79]]

 [[80 81 82 83]
  [84 85 86 87]
  [88 89 90 91]
  [92 93 94 95]
  [96 97 98 99]]]


Create a NumPy array of 10 random integers between 1 and 100

In [11]:
arrrr=np.random.randint(1,101,10)
print(arrrr)

[85  1  9 69 57 44 35 75  2  3]



Find the maximum and minimum of an array.


In [17]:
ar=np.random.randint(1,50,10)
print(ar)
maximum=np.max(ar)
minimum=np.min(ar)
print("Maximum value:", maximum)
print("Minimum value:", minimum)


[46  6 44 15 17 48 29 32 37 46]
Maximum value: 48
Minimum value: 6



Reshape a 1D array of 12 elements into a 3×4 matrix.


In [18]:
a=np.arange(1,13)
matrix=a.reshape(3,4)
print(matrix)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



Create an array of all even numbers between 50 and 100.


In [27]:
a=np.arange(50,101)
a=arr[arr%2==0]
print("even:",a)

even: [ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]


Given an array [1,2,3,4,5], compute the square of each element.



In [30]:
array=[1,2,3,4,5]
array=np.square(array)
print(array)

[ 1  4  9 16 25]


Create a 5×5 array of random numbers and find its mean.



In [34]:

array= np.random.randint(1, 101, (5, 5)) 
mean= np.mean(array)
print("5×5 :", array)
print("Mean:", mean)


5×5 : [[ 58  49  64   7  73]
 [ 14  80  54  24  99]
 [100  62  75  50  34]
 [ 68   3  55  41  87]
 [  9  83  26  24  69]]
Mean: 52.32


find the index of the maximum element in [10, 20, 50, 40, 30].

In [36]:
array=[10, 20, 50, 40, 30]
arr=np.argmax(array)
print(arr)

2


Create two arrays and perform element-wise addition, subtraction, multiplication, and division.

In [37]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([2, 4, 5, 8])
print(arr1)
print(arr2)
addition = arr1 + arr2
print("Addition:", addition)
subtraction = arr1 - arr2
print("Subtraction:", subtraction)
multiplication = arr1 * arr2
print("Multiplication:", multiplication)
division = arr1 / arr2
print("Division:", division)




[10 20 30 40]
[2 4 5 8]
Addition: [12 24 35 48]
Subtraction: [ 8 16 25 32]
Multiplication: [ 20  80 150 320]
Division: [5. 5. 6. 5.]


pandas 

Create a Pandas DataFrame from a dictionary of lists.



In [39]:

import pandas as pd   
df=pd.DataFrame({

"Name": ["rohan", "roshni", "rose"],

'Department': ['head_chef', 'commi', 'intern']})
print(df)

     Name Department
0   rohan  head_chef
1  roshni      commi
2    rose     intern


Read a CSV file into a DataFrame and display the first 5 rows.

In [46]:
import pandas as pd
data=pd.read_csv("Salary_Data.csv")
print(data.head())


    Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  52.0    Male        Master's           Director                 20.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  
3   60000.0  
4  200000.0  


Get the number of rows and columns of a DataFrame

In [47]:
print(data.shape)

(6704, 6)


Display all column names and their data types.

In [50]:
print(data.dtypes)

Age                    float64
Gender                  object
Education Level         object
Job Title               object
Years of Experience    float64
Salary                 float64
dtype: object


Select a single column ('Name') and multiple columns ('Name', 'Age') from a DataFrame.


In [53]:
a=data[["Education Level","Age"]]
print(a)

        Education Level   Age
0            Bachelor's  32.0
1              Master's  28.0
2                   PhD  45.0
3            Bachelor's  36.0
4              Master's  52.0
...                 ...   ...
6699                PhD  49.0
6700        High School  32.0
6701  Bachelor's Degree  30.0
6702    Master's Degree  46.0
6703        High School  26.0

[6704 rows x 2 columns]


Select the first 3 rows using iloc.


In [54]:
first = data.iloc[:3]
print(first)

    Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  


Find missing values in a DataFrame.


In [56]:
values=data.isnull()
print("Missing:\n",values)
count = data.isnull().sum()
print("\nNumber of missing values per column:\n",count)


Missing:
         Age  Gender  Education Level  Job Title  Years of Experience  Salary
0     False   False            False      False                False   False
1     False   False            False      False                False   False
2     False   False            False      False                False   False
3     False   False            False      False                False   False
4     False   False            False      False                False   False
...     ...     ...              ...        ...                  ...     ...
6699  False   False            False      False                False   False
6700  False   False            False      False                False   False
6701  False   False            False      False                False   False
6702  False   False            False      False                False   False
6703  False   False            False      False                False   False

[6704 rows x 6 columns]

Number of missing values per column:
 Ag


Replace all NaN values with "Unknown".


In [57]:
filled=data.fillna("Unknown")
print(filled)

       Age  Gender    Education Level              Job Title  \
0     32.0    Male         Bachelor's      Software Engineer   
1     28.0  Female           Master's           Data Analyst   
2     45.0    Male                PhD         Senior Manager   
3     36.0  Female         Bachelor's        Sales Associate   
4     52.0    Male           Master's               Director   
...    ...     ...                ...                    ...   
6699  49.0  Female                PhD  Director of Marketing   
6700  32.0    Male        High School        Sales Associate   
6701  30.0  Female  Bachelor's Degree      Financial Manager   
6702  46.0    Male    Master's Degree      Marketing Manager   
6703  26.0  Female        High School        Sales Executive   

     Years of Experience    Salary  
0                    5.0   90000.0  
1                    3.0   65000.0  
2                   15.0  150000.0  
3                    7.0   60000.0  
4                   20.0  200000.0  
...      

Sort the DataFrame by the 'Age' column in descending order.


In [58]:
sorted=data.sort_values(by='Age', ascending=False)
print(sorted)

       Age  Gender Education Level                    Job Title  \
1236  62.0    Male             PhD    Software Engineer Manager   
1305  62.0    Male             PhD    Software Engineer Manager   
1304  62.0    Male             PhD    Software Engineer Manager   
1258  62.0    Male             PhD    Software Engineer Manager   
1225  62.0    Male             PhD    Software Engineer Manager   
...    ...     ...             ...                          ...   
5057  21.0  Female     High School  Junior Sales Representative   
5031  21.0  Female     High School  Junior Sales Representative   
5018  21.0  Female     High School  Junior Sales Representative   
172    NaN     NaN             NaN                          NaN   
260    NaN     NaN             NaN                          NaN   

      Years of Experience    Salary  
1236                 20.0  200000.0  
1305                 19.0  200000.0  
1304                 20.0  200000.0  
1258                 19.0  200000.0  
1225 

Group the DataFrame by 'Department' and calculate the average salary.

In [60]:
average_salary=data.groupby('Job Title')['Salary'].mean()
print("\nAverage salary by Job Title:\n", average_salary)


Average salary by Job Title:
 Job Title
Account Manager              75000.000000
Accountant                   55000.000000
Administrative Assistant     50000.000000
Back end Developer          102352.561475
Business Analyst             77500.000000
                                ...      
UX Designer                  80000.000000
UX Researcher                65000.000000
VP of Finance               200000.000000
VP of Operations            190000.000000
Web Developer                66436.781609
Name: Salary, Length: 193, dtype: float64
