In [1]:
import numpy as np

In [2]:
list=[10,20,30,40,50,60,70,80]
array=np.array(list)
print(array)

[10 20 30 40 50 60 70 80]


In [5]:
multi_dimentional=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(multi_dimentional)
print(a)
type(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [7]:
list=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
a=np.linspace(0,1,7)
print(array)
print(a)

[10 20 30 40 50 60 70 80]
[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [10]:
list=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
print(list[0])
print(list[-1])
print(list[5])

1
20
6


In [11]:
li=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
print(li[0:])
print([1,2])



[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
[1, 2]
