In [13]:
import numpy as np

In [14]:
list=[10,20,30,40,50,60,70,80]
array=np.array(list)
print(array)

[10 20 30 40 50 60 70 80]


In [15]:
multi_dimentional=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(multi_dimentional)
print(a)
type(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


numpy.ndarray

In [16]:
list=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
a=np.linspace(0,1,7)
print(array)
print(a)

[10 20 30 40 50 60 70 80]
[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [17]:
list=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
print(list[0])
print(list[-1])
print(list[5])

1
20
6


In [18]:
li=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
print(li[0:])
print([1,2])



[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
[1, 2]


 create an array with 6 elements between 1 and 10

In [19]:
import numpy as np
array=np.arange(1,11)
print(array)


[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
arrayy=np.random.randint(1,11,6)
print(arrayy)

[5 1 8 5 4 9]


Perform array slicing

In [21]:
import numpy as np
array_slicing=np.array([1,2,3,4,5,6,7,8,9,10])
print(array_slicing[1:5])
print(array_slicing[::-1])
print(array_slicing[::2])
print(array_slicing[1:3:1])


[2 3 4 5]
[10  9  8  7  6  5  4  3  2  1]
[1 3 5 7 9]
[2 3]


Create an array of number from 1  to 10 and print only even numbers from that:

In [31]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
even=array[array % 2 == 0]
print(even)


[ 2  4  6  8 10]


Explore on Fancy Indexing

In [33]:
array=np.array([11,22,33,44,55,66,77,88,99])
print(array[-1])
print(array[0])
print(array[-5])
print(array[-1])
print(array[3])
print(array[-3])
print(array[-4])
print(array[4])









99
11
55
99
44
77
66
55
